#!/usr/bin/env python
# -*- coding: utf-8 -*-
'''Powerline prompt script.'''
import argparse

try:
	from powerline.core import Powerline
except ImportError:
	import os
	import sys
	sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
	from powerline.core import Powerline  # NOQA

parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument('side', nargs='?', default='all', choices=('all', 'left', 'right'))
parser.add_argument('--renderer_module', default='shell', choices=('shell', 'zsh_prompt'))
parser.add_argument('--ext', default='shell')

if __name__ == '__main__':
	args = parser.parse_args()
	pl = Powerline(ext=args.ext, renderer_module=args.renderer_module)
	segments = pl.renderer.get_theme().get_segments()
	if args.side != 'all':
		segments = [s for s in segments if s['side'] == args.side]
	print(pl.renderer.render(None, segments=segments))
