#!/usr/bin/env python
# -*- coding: utf-8 -*-
'''Powerline tmux statusline.'''
import argparse
import sys

try:
	from powerline.core import Powerline
except ImportError:
	import os
	sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
	from powerline.core import Powerline  # NOQA

parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument('side', nargs='?', default='all', choices=('all', 'left', 'right'))
parser.add_argument('--ext', default='tmux')

if __name__ == '__main__':
	args = parser.parse_args()
	powerline = Powerline(args.ext)
	segments = powerline.renderer.get_theme().get_segments()
	if args.side != 'all':
		segments = [s for s in segments if s['side'] == args.side]
	rendered = powerline.renderer.render(None, segments=segments)
	try:
		sys.stdout.write(rendered)
	except UnicodeEncodeError:
		sys.stdout.write(rendered.encode('utf-8'))
