#!/usr/bin/env python
# -*- coding: utf-8 -*-
'''Powerline prompt and statusline script.'''
import sys
import os

try:
	from powerline.shell import ShellPowerline, get_argparser
except ImportError:
	import os
	sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
	from powerline.shell import ShellPowerline, get_argparser  # NOQA

if __name__ == '__main__':
	args = get_argparser(description=__doc__).parse_args()
	powerline = ShellPowerline(args, run_once=True)
	rendered = powerline.render(
		width=args.width,
		side=args.side,
		segment_info={'args': args, 'environ': os.environ},
	)
	try:
		sys.stdout.write(rendered)
	except UnicodeEncodeError:
		sys.stdout.write(rendered.encode('utf-8'))
