#!/usr/bin/env python
# -*- coding: utf-8 -*-
'''Powerline prompt script.'''
import argparse
import sys

try:
	from powerline.core import Powerline
except ImportError:
	import os
	sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
	from powerline.core import Powerline  # NOQA

parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument('side', nargs='?', default=None, choices=('left', 'right'))
parser.add_argument('--renderer_module', default='shell', choices=('shell', 'zsh_prompt'))
parser.add_argument('--ext', default='shell')
parser.add_argument('--last_exit_code', default=None, type=int)
parser.add_argument('--last_pipe_status', default=None)

if __name__ == '__main__':
	args = parser.parse_args()
	powerline = Powerline(ext=args.ext, renderer_module=args.renderer_module, segment_info=args)
	rendered = powerline.renderer.render(side=args.side)
	try:
		sys.stdout.write(rendered)
	except UnicodeEncodeError:
		sys.stdout.write(rendered.encode('utf-8'))
