.TH "POWERLINE-CONFIG" "1" "October 2014" "Powerline" "Powerline manual"
.SH "NAME"
powerline-config \- Script used to obtain powerline configuration
.SH "SYNOPSIS"
\fIpowerline\-config\fR [\-h] {tmux,shell} ...
.SH "OPTIONS"
.SS "positional arguments:"
.IP
{tmux,shell}
.TP
tmux
Tmux\-specific commands
.TP
shell
Shell\-specific commands
.SS "optional arguments:"
.TP
\fB\-h\fR, \fB\-\-help\fR
show this help message and exit
.SH "SEE ALSO"
\fBpowerline\fR(1), \fBpowerline-daemon\fR(1), \fBpowerline-lint\fR(1)
.SH "AUTHORS"
Kim Silkebækken, Nikolay Pavlov, Kovid Goyal and contributors. The glyphs in the font patcher are created by Fabrizio Schiavi.
