.TH "POWERLINE-LINT" "1" "October 2014" "Powerline" "Powerline manual"
.SH "NAME"
powerline-lint \- Powerline configuration checker
.SH "SYNOPSIS"
\fIpowerline\-lint\fR [\-h] [\-p PATH] [\-d]
.PP
.SH "OPTIONS"
.SS "optional arguments:"
.TP
\fB\-h\fR, \fB\-\-help\fR
show this help message and exit
.HP
\fB\-p\fR PATH, \fB\-\-config_path\fR PATH
.HP
\fB\-d\fR, \fB\-\-debug\fR
.SH "SEE ALSO"
\fBpowerline\fR(1), \fBpowerline-config\fR(1), \fBpowerline-daemon\fR(1)
.SH "AUTHORS"
Kim Silkebækken, Nikolay Pavlov, Kovid Goyal and contributors. The glyphs in the font patcher are created by Fabrizio Schiavi.
